config/routes.rb
Rails.application.routes.draw do
  resources :toptens

  # Rails Wiki
  get "/railswiki", to: "railswiki#index"
  get "/railswiki/new", to: "railswiki#new"
  post "/railswiki", to: "railswiki#create"
  get "/railswiki/:id", to: "railswiki#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/railswiki.rb
class Railswiki < ApplicationRecord
end

app/models/topten.rb
class Topten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/railswiki_controller.rb
class RailswikiController < ApplicationController
    def index
        @railswiki = Railswiki.all
    end

    def new
        @railswiki = Railswiki.new
    end

    def create
        @railswiki = Railswiki.new(railswiki_params)
        @railswiki.save
        redirect_to_railswiki_path(@railswiki)
    end

    def show
        @railswiki = Railswiki.find(params[:id])
    end

    private

    def railswiki_params
        params.require(:railswiki).permit(:title, :content, :wiki_url, :wiki_tag)
    end
end

app/controllers/toptens_controller.rb
require "json"
require "open-uri"
require "nokogiri"
require 'uri'
require 'net/http'
require 'openssl'

class ToptensController < ApplicationController
  before_action :set_topten, only: [:show, :edit, :update, :destroy]

  # GET /toptens
  def index
    @toptens = Topten.all

    # url = "http://tmdb.lewagon.com/movie/top_rated"
    # movie_serialized = URI.open(url).read
    # @movies = JSON.parse(movie_serialized)

    url = "https://goo.gl/maps/Kdnv7bcw78Tye71XA"
    
    html_file = URI.open(url).read
    @html_doc = Nokogiri::HTML(html_file)

    # username = ""
    # user_id = ""
    # url = URI("https://instagram47.p.rapidapi.com/get_user_id?username=#{username}")
    # url = URI("https://instagram47.p.rapidapi.com/user_followers?userid=#{user_id}")
    # url = URI("https://instagram47.p.rapidapi.com/email_and_details?userid=#{user_id}")

    # http = Net::HTTP.new(url.host, url.port)
    # http.use_ssl = true
    # http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    # request = Net::HTTP::Get.new(url)
    # request["x-rapidapi-host"] = 'instagram47.p.rapidapi.com'
    # request["x-rapidapi-key"] = '0363c85d04msh3370cfb927787c3p1afecdjsn2b8cab3ddff8'

    # @insta = http.request(request)
  end

  # GET /toptens/1
  def show
  end

  # GET /toptens/new
  def new
    @topten = Topten.new
  end

  # GET /toptens/1/edit
  def edit
  end

  # POST /toptens
  def create
    @topten = Topten.new(topten_params)

    if @topten.save
      redirect_to @topten, notice: 'Topten was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /toptens/1
  def update
    if @topten.update(topten_params)
      redirect_to @topten, notice: 'Topten was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /toptens/1
  def destroy
    @topten.destroy
    redirect_to toptens_url, notice: 'Topten was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topten
      @topten = Topten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topten_params
      params.require(:topten).permit(:name, :comment, :address, :stars)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railswiki_helper.rb
module RailswikiHelper
end

app/helpers/toptens_helper.rb
module ToptensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlayground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/railswiki/index.html.erb
<h1>Rails Wiki INDEX</h1>

<%= @wiki %>

app/views/railswiki/new.html.erb
<h1>Rails Wiki NEW</h2>

<%= @railswiki %>

<%= form_for(@railswiki) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/railswiki/show.html.erb
<h1>Rails Wiki SHOW</h1>

<p><%= @railswiki.title %></p>
<p><%= @railswiki.content %></p>
<p><%= @railswiki.wiki_url %></p>
<p><%= @railswiki.wiki_tag %></p>

app/views/toptens/_form.html.erb
<%= simple_form_for(@topten) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :comment %>
    <%= f.input :address %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/toptens/edit.html.erb
<h1>Editing Topten</h1>

<%= render 'form', topten: @topten %>

<%= link_to 'Show', @topten %> |
<%= link_to 'Back', toptens_path %>

app/views/toptens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Toptens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Address</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @toptens.each do |topten| %>
      <tr>
        <td><%= topten.name %></td>
        <td><%= topten.comment %></td>
        <td><%= topten.address %></td>
        <td><%= topten.stars %></td>
        <td><%= link_to 'Show', topten %></td>
        <td><%= link_to 'Edit', edit_topten_path(topten) %></td>
        <td><%= link_to 'Destroy', topten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% @html_doc.search("div").each do |element| %>
  <%= element %>
<% end %>

<br>

<%= link_to 'New Topten', new_topten_path %>

app/views/toptens/new.html.erb
<h1>New Topten</h1>

<%= render 'form', topten: @topten %>

<%= link_to 'Back', toptens_path %>

app/views/toptens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topten.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @topten.comment %>
</p>

<p>
  <strong>Address:</strong>
  <%= @topten.address %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @topten.stars %>
</p>

<%= link_to 'Edit', edit_topten_path(@topten) %> |
<%= link_to 'Back', toptens_path %>